# Generated by Django 2.1.7 on 2019-07-02 12:33

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=4)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('parameters', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('input_types', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('output_types', picklefield.fields.PickledObjectField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('methods', picklefield.fields.PickledObjectField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebService.Request')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='REST.Method')),
            ],
            bases=('WebService.request',),
        ),
        migrations.CreateModel(
            name='RestWebService',
            fields=[
                ('webservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebService.WebService')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('paths', picklefield.fields.PickledObjectField(editable=False, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('WebService.webservice',),
        ),
        migrations.CreateModel(
            name='SwaggerResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_code', models.CharField(choices=[('100', '100'), ('101', '101'), ('102', '102'), ('103', '103'), ('200', '200'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('206', '206'), ('207', '207'), ('208', '208'), ('226', '226'), ('300', '300'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305'), ('307', '307'), ('308', '308'), ('400', '400'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404'), ('405', '405'), ('406', '406'), ('407', '407'), ('408', '408'), ('409', '409'), ('410', '410'), ('411', '411'), ('412', '412'), ('413', '413'), ('414', '414'), ('415', '415'), ('416', '416'), ('417', '417'), ('421', '421'), ('422', '422'), ('423', '423'), ('424', '424'), ('425', '425'), ('426', '426'), ('428', '428'), ('429', '429'), ('431', '431'), ('451', '451'), ('500', '500'), ('501', '501'), ('502', '502'), ('503', '503'), ('504', '504'), ('505', '505'), ('506', '506'), ('507', '507'), ('508', '508'), ('510', '510'), ('511', '511')], max_length=3)),
                ('description', models.TextField(editable=False)),
                ('schema', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.Method')),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='web_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.RestWebService'),
        ),
        migrations.AddField(
            model_name='method',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.Path'),
        ),
    ]
