# Generated by Django 2.1.7 on 2019-07-02 12:33

import WebService.validators
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=4)),
                ('data', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('files', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('headers', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('category', models.CharField(choices=[('MALICIOUS', 'Malicious'), ('NON-MALICIOUS', 'Non-malicious')], max_length=13)),
                ('pattern', models.CharField(max_length=200, null=True)),
                ('attack_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Attacks.Attack')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(editable=False)),
                ('http_status_code', models.CharField(choices=[('100', '100'), ('101', '101'), ('102', '102'), ('103', '103'), ('200', '200'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('206', '206'), ('207', '207'), ('208', '208'), ('226', '226'), ('300', '300'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305'), ('307', '307'), ('308', '308'), ('400', '400'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404'), ('405', '405'), ('406', '406'), ('407', '407'), ('408', '408'), ('409', '409'), ('410', '410'), ('411', '411'), ('412', '412'), ('413', '413'), ('414', '414'), ('415', '415'), ('416', '416'), ('417', '417'), ('421', '421'), ('422', '422'), ('423', '423'), ('424', '424'), ('425', '425'), ('426', '426'), ('428', '428'), ('429', '429'), ('431', '431'), ('451', '451'), ('500', '500'), ('501', '501'), ('502', '502'), ('503', '503'), ('504', '504'), ('505', '505'), ('506', '506'), ('507', '507'), ('508', '508'), ('510', '510'), ('511', '511')], max_length=3)),
                ('time_to_first_byte', models.FloatField()),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebService.Request')),
            ],
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('SOAP', 'SOAP'), ('REST', 'REST')], default='SOAP', max_length=4, verbose_name='Web Service Type')),
                ('description_file', models.FileField(blank=True, upload_to='', validators=[WebService.validators.validate_description_file], verbose_name='Description file')),
                ('description_url', models.URLField(blank=True, validators=[WebService.validators.validate_url_extension, WebService.validators.validate_description_url], verbose_name='Description URL')),
                ('documentation', models.TextField(editable=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
