# Generated by Django 2.1.7 on 2019-07-02 12:33

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('soap_version', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('documentation', models.TextField(editable=False)),
                ('parameters', picklefield.fields.PickledObjectField(editable=False)),
                ('soap_action', models.CharField(default='', max_length=1000)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SOAP.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='SoapRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebService.Request')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SOAP.Operation')),
            ],
            bases=('WebService.request',),
        ),
        migrations.CreateModel(
            name='SoapWebService',
            fields=[
                ('webservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WebService.WebService')),
                ('address', models.URLField()),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('WebService.webservice',),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='web_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SOAP.SoapWebService'),
        ),
    ]
