HTTP_STATUS_CODES_MEANINGS = [
    ('100', 'Continue'),
    ('101', 'Switching Protocols'),
    ('102', 'Processing'),
    ('103', 'Early Hints'),
    ('200', 'OK'),
    ('201', 'Created'),
    ('202', 'Accepted'),
    ('203', 'Non - Authoritative Information'),
    ('204', 'No Content'),
    ('205', 'Reset Content'),
    ('206', 'Partial Content'),
    ('207', 'Multi - Status'),
    ('208', 'Already Reported'),
    ('226', 'IM Used'),
    ('300', 'Multiple Choices'),
    ('301', 'Moved Permanently'),
    ('302', 'Found'),
    ('303', 'See Other'),
    ('304', 'Not Modified'),
    ('305', 'Use Proxy'),
    ('307', 'Temporary Redirect'),
    ('308', 'Permanent Redirect'),
    ('400', 'Bad Request'),
    ('401', 'Unauthorized'),
    ('402', 'Payment Required'),
    ('403', 'Forbidden'),
    ('404', 'Not Found'),
    ('405', 'Method Not Allowed'),
    ('406', 'Not Acceptable'),
    ('407', 'Proxy Authentication Required'),
    ('408', 'Request Timeout'),
    ('409', 'Conflict'),
    ('410', 'Gone'),
    ('411', 'Length Required'),
    ('412', 'Precondition Failed'),
    ('413', 'Payload Too Large'),
    ('414', 'URI Too Long'),
    ('415', 'Unsupported Media Type'),
    ('416', 'Range Not Satisfiable'),
    ('417', 'Expectation Failed'),
    ('421', 'Misdirected Request'),
    ('422', 'Unprocessable Entity'),
    ('423', 'Locked'),
    ('424', 'Failed Dependency'),
    ('425', 'Too Early'),
    ('426', 'Upgrade Required'),
    ('428', 'Precondition Required'),
    ('429', 'Too Many Requests'),
    ('431', 'Request Header Fields Too Large'),
    ('451', 'Unavailable For Legal Reasons'),
    ('500', 'Internal Server Error'),
    ('501', 'Not Implemented'),
    ('502', 'Bad Gateway'),
    ('503', 'Service Unavailable'),
    ('504', 'Gateway Timeout'),
    ('505', 'HTTP Version Not Supported'),
    ('506', 'Variant Also Negotiates'),
    ('507', 'Insufficient Storage'),
    ('508', 'Loop Detected'),
    ('510', 'Not Extended'),
    ('511', 'Network Authentication Required')
]

HTTP_STATUS_CODES = [
    ('100','100'),
    ('101','101'),
    ('102','102'),
    ('103','103'),
    ('200','200'),
    ('201','201'),
    ('202','202'),
    ('203','203'),
    ('204','204'),
    ('205','205'),
    ('206','206'),
    ('207','207'),
    ('208','208'),
    ('226','226'),
    ('300','300'),
    ('301','301'),
    ('302','302'),
    ('303','303'),
    ('304','304'),
    ('305','305'),
    ('307','307'),
    ('308','308'),
    ('400','400'),
    ('401','401'),
    ('402','402'),
    ('403','403'),
    ('404','404'),
    ('405','405'),
    ('406','406'),
    ('407','407'),
    ('408','408'),
    ('409','409'),
    ('410','410'),
    ('411','411'),
    ('412','412'),
    ('413','413'),
    ('414','414'),
    ('415','415'),
    ('416','416'),
    ('417','417'),
    ('421','421'),
    ('422','422'),
    ('423','423'),
    ('424','424'),
    ('425','425'),
    ('426','426'),
    ('428','428'),
    ('429','429'),
    ('431','431'),
    ('451','451'),
    ('500','500'),
    ('501','501'),
    ('502','502'),
    ('503','503'),
    ('504','504'),
    ('505','505'),
    ('506','506'),
    ('507','507'),
    ('508','508'),
    ('510','510'),
    ('511','511')
]

HTTP_METHODS = [
    ('GET', 'GET'),
    ('POST', 'POST'),
    ('PUT', 'PUT'),
    ('PATCH', 'PATCH'),
    ('DELETE', 'DELETE'),
    ('HEAD', 'HEAD'),
    ('OPTIONS', 'OPTIONS')
]


SOAP = 'SOAP'
REST = 'REST'

WS_TYPES = [
    (SOAP, 'SOAP'),
    (REST, 'REST')
]

BAD = 'MALICIOUS'
GOOD = 'NON-MALICIOUS'
REQUESTS_TYPES = (
    (BAD, 'Malicious'),
    (GOOD, 'Non-malicious'),
)


VALID_MIME_TYPES = ['application/wsdl+xml', 'text/xml', 'text/plain']


DATA_TYPES = [
    ('string', 'String'),
    ('duration', 'Duration'),
    ('dateTime', 'Date Time'),
    ('dateTimeStamp', 'Date Time Stamp'),
    ('date', 'Date'),
    ('time', 'Time'),
    ('gYear', 'Year'),
    ('gMonth', 'Month'),
    ('gDay', 'Day'),
    ('gYearMonth', 'Year Month'),
    ('gMonthDay', 'Month Day'),
    ('boolean', 'Boolean'),
    ('int', 'Integer'),
    ('short', 'Short'),
    ('byte', 'Byte'),
    ('float', 'Float'),
    ('double', 'Double'),
    ('decimal', 'Decimal'),
    ('integer', 'Integer'),
    ('long', 'Long'),
    ('negativeInteger', 'Negative Integer'),
    ('nonNegativeInteger', 'Non Negative Integer'),
    ('positiveInteger', 'Positive Integer'),
    ('nonPositiveInteger', 'Non Positive Integer'),
    ('unsignedLong', 'Unsigned Long'),
    ('unsignedInt', 'Unsigned Integer'),
    ('unsignedShort', 'Unsigned Short'),
    ('unsignedByte', 'Unsigned Byte'),
    ('NOTATION', 'Notation'),
    ('QName', 'Qualified Name'),
    ('anyURI', 'AnyURI'),
    ('base64Binary', 'Base64Binary'),
    ('hexBinary', 'HexBinary'),
    ('normalizedString', 'Normalized String'),
    ('token', 'Token'),
    ('language', 'Language'),
    ('NMTOKEN', 'NM Token'),
    ('NMTOKENS', 'NM Tokens'),
    ('Name', 'Name'),
    ('NCName', 'NC Name'),
    ('ID', 'ID'),
    ('IDREF', 'ID Ref'),
    ('IDREFS', 'ID Refs'),
    ('ENTITY', 'Entity'),
    ('ENTITIES', 'Entities')
]

DATA_TYPES_LIST = [
    'string',
    'duration',
    'datetime',
    'datetimestamp',
    'date',
    'time',
    'gyear',
    'gmonth',
    'gday',
    'gyearmonth',
    'gmonthday',
    'boolean',
    'int',
    'short',
    'byte',
    'float',
    'double',
    'decimal',
    'integer',
    'long',
    'negativeinteger',
    'nonnegativeinteger',
    'positiveinteger',
    'nonpositiveinteger',
    'unsignedlong',
    'unsignedint',
    'unsignedshort',
    'unsignedbyte',
    'notation',
    'qname',
    'anyuri',
    'base64binary',
    'hexbinary',
    'normalizedstring',
    'token',
    'language',
    'nmtoken',
    'nmtokens',
    'name',
    'ncname',
    'id',
    'idref',
    'idrefs',
    'entity',
    'entities'
]


TIMEOUT = 15